name = "projectrc"
main = "src/index.ts"
compatibility_date = "2023-08-20"
routes = [ { pattern = "cron.projectrc.luxass.dev", custom_domain = true } ]

[triggers]
# crons = [ "0 0 * * *" ]
crons = [
  # cron job for every 10 minutes
  "*/5 * * * *"
]
